#Example configuration options that can be placed in your main SiriProxy config.yml

##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################
    
    - name: 'Twitter'
      git: 'git://github.com/netpro2k/SiriProxy-Twitter.git'
      consumer_key: "YOUR_KEY" 
      consumer_secret: "YOUR_SECRET"
      oauth_token: "YOUR_TOKEN" 
      oauth_token_secret: "YOUR_TOKEN_SECRET"
